### ISSUE TITLE
installation instructions?

### ISSUE THREAD

**Issue by brabalan** [c-cube/ezcurl#1]
I tried to run `opam install ezcurl` and it's not finding the package. Is this library on opam?

**Comment by c-cube** [comment]
hi, no, it's not released yet, and I'm not using it right now. You can `opam pin https://github.com/c-cube/ezcurl.git#master` if you want to give it a try :)

**Comment by brabalan** [comment]
Thanks, I'll do that.

**Comment by brabalan** [comment]
It works like a charm. Thanks!
