### ISSUE TITLE
POST or PUT with request body results in one-second delay

### ISSUE THREAD

**Issue by cemerick** [c-cube/ezcurl#12]
When sending a request that includes some body content (via `~content`), curl will by default not send that body for up to one second, waiting for a `100 Continue` intermediate response from the server. Details on this behaviour can be found here:

* https://everything.curl.dev/http/post/expect100
* https://daniel.haxx.se/blog/2020/02/27/expect-tweaks-in-curl/

What's odd is that libcurl/ocurl being used by ezcurl will exhibit this behaviour for _any_ size request body, even hundreds of bytes. That doesn't align with what's been documented, and the only way to control the default threshold is via a libcurl compile-time constant (`EXPECT_100_THRESHOLD`). Aside from libcurl sending an `Expect` header and waiting, it appears to always send `Transfer-Encoding: chunked`, so it appears that ezcurl/ocurl is failing to set the request body size, even though it certainly seems to try! https://github.com/c-cube/ezcurl/blob/f70f25d951d4a9cb49e23906703fc88330088b11/src/core/Ezcurl_core.ml#L321

Per the `curl`/`libcurl` docs, an unobvious workaround exists though: set an empty `Expect` header on all your requests that include a body, i.e. `~headers:["Expect", ""]`. This disables curl's default behaviour (regardless of request body size setting or not), and eliminates the one-second observed delay in the completion of the request.

The real fix for this problem would be to investigate and fix how ezcurl/ocurl's efforts at setting the request body size are insufficient.

**Comment by c-cube** [comment]
Interesting bug indeed. I think it's fine to send `"Expect:"` for now, and see later why size isn't set properly.

As an aside: how should we test for this kind of thing? Is there a local test httpd that doesn't handle 100: Continue? I'm not even sure how to test this locally :)

**Comment by cemerick** [comment]
Just based on the curl docs and blog post I linked, it sounds like few to no servers actually support the expect/continue semantic:

> Since this mandatory header is widely not understood or simply ignored by HTTP/1.1 servers, clients that issue this header will have a rather short timeout and if no response has been received within that period it will proceed and send the data even without a 100.

I know for sure that Dream does not support `100 Continue` responses (except for websocket setups), so that might be the easiest way to stand up a suitable test environment?

**Comment by c-cube** [comment]
Ah, interesting. Tiny_httpd has [some basic handling](https://github.com/c-cube/tiny_httpd/blob/master/src/Tiny_httpd_server.ml#L800-L806) of it :sweat_smile: .

**Comment by cemerick** [comment]
Nice!

It looks like PUTs are supposed to use the "INFILESIZE" option that ezcurl is already touching though... https://curl.se/libcurl/c/CURLOPT_UPLOAD.html

**Comment by c-cube** [comment]
The patch in #13 will set INFILESIZE if the method is not POST :)

**Comment by c-cube** [comment]
ping @cemerick if you have time to test #13 :)

**Comment by cemerick** [comment]
@c-cube Will do, though there's still a spurious `eprintf` in there! :-P
