### ISSUE TITLE
Ezcurl.http is blowing away custom configs

### ISSUE THREAD

**Issue by yawaramin** [c-cube/ezcurl#7]
E.g.:

```ocaml
#require "ezcurl";;
#install_printer Ezcurl.pp_response;;

let cookie_jar = "cookies.txt";;

let test url =
  let curl = Curl.init () in
  let finally () = Curl.cleanup curl in

  Curl.set_cookiejar curl cookie_jar;
  Curl.set_cookiefile curl cookie_jar;

  Fun.protect ~finally @@ Ezcurl.get ~client:curl ~url;;
```

Then when we try to use this we see that the cookie jar file `cookies.txt` is never generated:

```ocaml
test "https://exchange-rates-api.oanda.com/health"
```

**Comment by c-cube** [comment]
Right, currently if you pass a client it is `Curl.reset` first. This is a bug indeed: besides this issue, it makes the existing functions like `?set_opts` useless since the client will ignore them.

**Comment by c-cube** [comment]
I tried with this patch, and it does  create `cookies.txt`. If you can also test on your real use case before I merge and release, that'd be great :)

**Comment by yawaramin** [comment]
That works for me locally, thanks!
